### ISSUE TITLE
SvelteKit and Vite CSS :global Error

### ISSUE THREAD

**Issue by FortyGazelle700** [huntabyte/vaul-svelte#17]
Whenever I try to use the `Drawer.Root` component in your port of `shadcn-svelte`, it throws an error like this:
```
[plugin:vite-plugin-svelte] {{PROJECT ROOT}}/node_modules/vaul-svelte/dist/vaul/components/root.svelte:145:9 Expected a valid CSS identifier
```
```css
{{PROJECT ROOT}}/node_modules/vaul-svelte/dist/vaul/components/root.svelte:145:9

143|  	}
144|  
145|  	:global(
   |           ^
146|  			[data-vaul-overlay][data-vaul-snap-points='true']:not(
147|  					[data-vaul-snap-points-overlay='true']
```

**Comment by huntabyte** [comment]
What version of Svelte are you using?

**Comment by huntabyte** [comment]
This is an issue related to Svelte 5, which this project won't _officially_ support until it's stable. If you're getting compiler errors raise an issue with Svelte to bring it to the team's awareness!

**Comment by FortyGazelle700** [comment]
Okay, thank you for the response, and I apologize for the inconvenience.
