### ISSUE TITLE
Bug: Triggering the Drawer right after closing it causes it to open and close immediately

### ISSUE THREAD

**Issue by basokant** [huntabyte/vaul-svelte#3]
https://github.com/huntabyte/vaul-svelte/assets/70033855/61edf2e0-93e6-4305-8068-f9380a1e6647

This bug was observed on both Chrome and Safari.

**Comment by code406** [comment]
Similar experience in Chrome for Android. Tapping the button right after closing the dialog makes it not trigger the dialog.

https://github.com/huntabyte/vaul-svelte/assets/36109227/8427714c-7d19-4205-80d1-2d1b09fbde02

(Hope you can see the touch indicator, it's white over a white background...)

**Comment by basokant** [comment]
This was fixed in https://github.com/huntabyte/vaul-svelte/commit/c55703ea3841a34acb6d97e67154d87aafeb0c98. See below demo:

https://github.com/huntabyte/vaul-svelte/assets/70033855/b9e676a9-4ea5-4167-8cf7-0d2642806890

**Comment by basokant** [comment]
> Similar experience in Chrome for Android. Tapping the button right after closing the dialog makes it not trigger the dialog.
> 
>  screen-20231231-020250.2.mp4 
> (Hope you can see the touch indicator, it's white over a white background...)

I believe this is desired behaviour, you shouldn't be able to reopen it that quickly, which is why the button doesn't work. Before it was quickly opening and closing
