### ISSUE TITLE
Configurable Drawer Opening Direction

### ISSUE THREAD

**Issue by theetherGit** [huntabyte/vaul-svelte#37]
### Feature

As new version of Vaul React have new direction prop for drawer, we can add that from https://github.com/emilkowalski/vaul/pull/187.

I can work on this if you allow.

### Relevent

https://github.com/emilkowalski/vaul/pull/187 - Pull Request for direction functionality in drawer.

> It got duplicated by mistake, I had this written yesterday.

**Comment by huntabyte** [comment]
Duplicate of #36
