### ISSUE TITLE
(Safari) Dragging no longer works in Safari.

### ISSUE THREAD

**Issue by mateuszlewko** [huntabyte/vaul-svelte#45]
### Describe the bug

It looks like the newest release broke dragging in Safari (macOS). Dragging works as expected on Chrome.

### Reproduction

Go to https://www.vaul-svelte.com, open drawer, try dragging from top in Safari.

### System Info

```bash
Browsers:
    Safari: 17.3
  npmPackages:
    @sveltejs/kit: ^2.5.0 => 2.5.0
    bits-ui: ^0.16.0 => 0.16.0
    svelte: ^4.2.9 => 4.2.9
    typescript: ^5.3.3 => 5.3.3
    vaul-svelte: ^0.2.1 => 0.2.1
```

### Severity

annoyance

**Comment by huntabyte** [comment]
This was actually the PR that broke it for Safari it appears 🤔, which was smaller than the latest.
https://github.com/huntabyte/vaul-svelte/pull/38

My hunch tells me its something to do with touch events and Safari, but I'll investigate further.
