### ISSUE TITLE
Requires Double Click to Reopen After Swipe Close

### ISSUE THREAD

**Issue by PrabhuKiran8790** [huntabyte/vaul-svelte#5]
## Issue Description:
On mobile devices, when I swipe it down to close, I can't reopen it by clicking the button just once; instead, I need to click the button twice. This behavior is inconsistent with the expected behavior, where the drawer should open again with a single click after being closed by swiping down.

## Steps to Reproduce:

1. Open the drawer by clicking the button.
2. Swipe the drawer down to close it.
3. Attempt to reopen the drawer by clicking the button.

## Expected Behavior:
The drawer should reopen with a single click after being closed by swiping down.

## Actual Behavior:
The drawer requires two clicks to reopen after being closed by swiping down or need to click outside to enable the button.

**Comment by PrabhuKiran8790** [comment]
https://github.com/huntabyte/vaul-svelte/assets/86601758/55355c96-d6ee-4c2f-b0e9-9f9025d04936

**Comment by JamieDW** [comment]
Thanks PrabhuKiran8790, I also noticed this. One thing I found is If you swipe **all** the way down this doesn't happen. 

[screen-20231231-230735.webm](https://github.com/huntabyte/vaul-svelte/assets/18234837/820a20f0-2a24-48ca-beaa-a093b71825fb)

**Comment by PrabhuKiran8790** [comment]
Yes Jamie! This doesn't happen if you swipe all the way down. Maybe an invisible overlay or an issue with swipe down gesture.

**Comment by basokant** [comment]
@PrabhuKiran8790 I believe that you should not be able to reopen the drawer until the drawer is completely closed. The double click behaviour that you noticed is just a result of the animation taking longer than you expect. You are right about the overlay, it only unmounts when the drawer is completely closed.

**Comment by huntabyte** [comment]
This is likely something that the user would be able to handle on the UI side, which could be disabling the button while the `open` state of the drawer is true.

**Comment by PrabhuKiran8790** [comment]
I just noticed that the animation takes a little longer and I can reopen the drawer without the double click.
I'm closing this issue. Great work @huntabyte.
