### ISSUE TITLE
background: black inline style added to body but not cleaned up

### ISSUE THREAD

**Issue by khromov** [huntabyte/vaul-svelte#56]
### Describe the bug

See repro below. The demo site has an overlay div that makes this problem not visible but in my app the background suddenly turns black after opening the modal.

https://github.com/huntabyte/vaul-svelte/assets/1207507/59cba726-f62d-4309-842b-1fe9dadb7375

### Reproduction

1. Go to https://www.vaul-svelte.com/
2. Open web inspector, check body, no inline styles present
3. Open Drawer, close drawer
4. Body now has `background: black;` inline style

### System Info

```bash
-
```

### Severity

annoyance

**Comment by shyakadavis** [comment]
Hi;

Found a fix for this. Will send a P.R in a few. 🙂

**Comment by khromov** [comment]
Much appreciated!

**Comment by shyakadavis** [comment]
Btw, @khromov I love your blog and snippets sites. Had not checked on them for a while, though. Let me see what new stuff you got there. 🙂
