### ISSUE TITLE
Doesn't work after certain svelte 5 version

### ISSUE THREAD

**Issue by blaketradedev** [huntabyte/vaul-svelte#89]
### Describe the bug

It works on svelte version ^5.0.0-next.184

But on ^5.0.0-next.222, it stops working, would be really great if it could be fixed

### Reproduction

It works on svelte version ^5.0.0-next.184

But on ^5.0.0-next.222, it stops working, would be really great if it could be fixed

I can't suddenly touch and drag to close the drawer when I update to 222

### System Info

```bash
Sveltekit ^5.0.0-next.184
```

### Severity

annoyance

**Comment by mustafa0x** [comment]
works fine hre
