### ISSUE TITLE
Svelte 3.x support?

### ISSUE THREAD

**Issue by petr24** [huntabyte/vaul-svelte#91]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

Hey guys, love your work, and everything you do!

Would it be possible to support Svelte 3.x, i'm assuming it's not as simple as downgrading svelte in package.json?

I have a few svelte projects, and some of them are still on 3.x, and can't upgrade to 4 yet. 

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
We aren't planning to support 2 major versions back, we just don't have the resources to support to maintain multiple majors.
